// flow-typed signature: 77ae34dc3c61451e5125ece6c8d22eee
// flow-typed version: <<STUB>>/html-escape_v^2.0.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-escape'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-escape' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-escape/example' {
  declare module.exports: any;
}

declare module 'html-escape/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-escape/example.js' {
  declare module.exports: $Exports<'html-escape/example'>;
}
declare module 'html-escape/index' {
  declare module.exports: $Exports<'html-escape'>;
}
declare module 'html-escape/index.js' {
  declare module.exports: $Exports<'html-escape'>;
}
declare module 'html-escape/test.js' {
  declare module.exports: $Exports<'html-escape/test'>;
}
