// flow-typed signature: e24c25c2f6f15f237b070fde2308f32b
// flow-typed version: <<STUB>>/iconv_v^2.2.3/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'iconv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'iconv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'iconv/lib/iconv' {
  declare module.exports: any;
}

declare module 'iconv/test/test-basic' {
  declare module.exports: any;
}

declare module 'iconv/test/test-big-buffer' {
  declare module.exports: any;
}

declare module 'iconv/test/test-stream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'iconv/lib/iconv.js' {
  declare module.exports: $Exports<'iconv/lib/iconv'>;
}
declare module 'iconv/test/test-basic.js' {
  declare module.exports: $Exports<'iconv/test/test-basic'>;
}
declare module 'iconv/test/test-big-buffer.js' {
  declare module.exports: $Exports<'iconv/test/test-big-buffer'>;
}
declare module 'iconv/test/test-stream.js' {
  declare module.exports: $Exports<'iconv/test/test-stream'>;
}
