// flow-typed signature: 1f89bf20993c8a83ad2ebf3fcf4a6ad6
// flow-typed version: <<STUB>>/method-override_v^2.3.8/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'method-override'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'method-override' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'method-override/index' {
  declare module.exports: $Exports<'method-override'>;
}
declare module 'method-override/index.js' {
  declare module.exports: $Exports<'method-override'>;
}
