// flow-typed signature: 4477ce54f4c56766df9d70a7a2a62fe1
// flow-typed version: <<STUB>>/node-slackr_v^0.1.4/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-slackr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-slackr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-slackr/lib/slack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-slackr/index' {
  declare module.exports: $Exports<'node-slackr'>;
}
declare module 'node-slackr/index.js' {
  declare module.exports: $Exports<'node-slackr'>;
}
declare module 'node-slackr/lib/slack.js' {
  declare module.exports: $Exports<'node-slackr/lib/slack'>;
}
