// flow-typed signature: 254b2bb7475ab4f942b41938a91043e6
// flow-typed version: <<STUB>>/pmx_v^1.1.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pmx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pmx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pmx/lib/actions' {
  declare module.exports: any;
}

declare module 'pmx/lib/actions/default' {
  declare module.exports: any;
}

declare module 'pmx/lib/common' {
  declare module.exports: any;
}

declare module 'pmx/lib/configuration' {
  declare module.exports: any;
}

declare module 'pmx/lib/events' {
  declare module.exports: any;
}

declare module 'pmx/lib/monitor' {
  declare module.exports: any;
}

declare module 'pmx/lib/network' {
  declare module.exports: any;
}

declare module 'pmx/lib/notify' {
  declare module.exports: any;
}

declare module 'pmx/lib/pmx' {
  declare module.exports: any;
}

declare module 'pmx/lib/Probe' {
  declare module.exports: any;
}

declare module 'pmx/lib/probes/express' {
  declare module.exports: any;
}

declare module 'pmx/lib/probes/modules' {
  declare module.exports: any;
}

declare module 'pmx/lib/probes/mongo' {
  declare module.exports: any;
}

declare module 'pmx/lib/probes/pacemaker' {
  declare module.exports: any;
}

declare module 'pmx/lib/probes/profiling' {
  declare module.exports: any;
}

declare module 'pmx/lib/transaction' {
  declare module.exports: any;
}

declare module 'pmx/lib/utils/alert' {
  declare module.exports: any;
}

declare module 'pmx/lib/utils/autocast' {
  declare module.exports: any;
}

declare module 'pmx/lib/utils/BinaryHeap' {
  declare module.exports: any;
}

declare module 'pmx/lib/utils/datachecker' {
  declare module.exports: any;
}

declare module 'pmx/lib/utils/EDS' {
  declare module.exports: any;
}

declare module 'pmx/lib/utils/error-callsites/index' {
  declare module.exports: any;
}

declare module 'pmx/lib/utils/error-callsites/node-0.10-formatter' {
  declare module.exports: any;
}

declare module 'pmx/lib/utils/EWMA' {
  declare module.exports: any;
}

declare module 'pmx/lib/utils/fixedQueue' {
  declare module.exports: any;
}

declare module 'pmx/lib/utils/probes/Counter' {
  declare module.exports: any;
}

declare module 'pmx/lib/utils/probes/Histogram' {
  declare module.exports: any;
}

declare module 'pmx/lib/utils/probes/Meter' {
  declare module.exports: any;
}

declare module 'pmx/lib/utils/proxy' {
  declare module.exports: any;
}

declare module 'pmx/lib/utils/sample' {
  declare module.exports: any;
}

declare module 'pmx/lib/utils/transport' {
  declare module.exports: any;
}

declare module 'pmx/lib/utils/units' {
  declare module.exports: any;
}

declare module 'pmx/lib/wrapper/simple_http' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pmx/index' {
  declare module.exports: $Exports<'pmx'>;
}
declare module 'pmx/index.js' {
  declare module.exports: $Exports<'pmx'>;
}
declare module 'pmx/lib/actions.js' {
  declare module.exports: $Exports<'pmx/lib/actions'>;
}
declare module 'pmx/lib/actions/default.js' {
  declare module.exports: $Exports<'pmx/lib/actions/default'>;
}
declare module 'pmx/lib/common.js' {
  declare module.exports: $Exports<'pmx/lib/common'>;
}
declare module 'pmx/lib/configuration.js' {
  declare module.exports: $Exports<'pmx/lib/configuration'>;
}
declare module 'pmx/lib/events.js' {
  declare module.exports: $Exports<'pmx/lib/events'>;
}
declare module 'pmx/lib/monitor.js' {
  declare module.exports: $Exports<'pmx/lib/monitor'>;
}
declare module 'pmx/lib/network.js' {
  declare module.exports: $Exports<'pmx/lib/network'>;
}
declare module 'pmx/lib/notify.js' {
  declare module.exports: $Exports<'pmx/lib/notify'>;
}
declare module 'pmx/lib/pmx.js' {
  declare module.exports: $Exports<'pmx/lib/pmx'>;
}
declare module 'pmx/lib/Probe.js' {
  declare module.exports: $Exports<'pmx/lib/Probe'>;
}
declare module 'pmx/lib/probes/express.js' {
  declare module.exports: $Exports<'pmx/lib/probes/express'>;
}
declare module 'pmx/lib/probes/modules.js' {
  declare module.exports: $Exports<'pmx/lib/probes/modules'>;
}
declare module 'pmx/lib/probes/mongo.js' {
  declare module.exports: $Exports<'pmx/lib/probes/mongo'>;
}
declare module 'pmx/lib/probes/pacemaker.js' {
  declare module.exports: $Exports<'pmx/lib/probes/pacemaker'>;
}
declare module 'pmx/lib/probes/profiling.js' {
  declare module.exports: $Exports<'pmx/lib/probes/profiling'>;
}
declare module 'pmx/lib/transaction.js' {
  declare module.exports: $Exports<'pmx/lib/transaction'>;
}
declare module 'pmx/lib/utils/alert.js' {
  declare module.exports: $Exports<'pmx/lib/utils/alert'>;
}
declare module 'pmx/lib/utils/autocast.js' {
  declare module.exports: $Exports<'pmx/lib/utils/autocast'>;
}
declare module 'pmx/lib/utils/BinaryHeap.js' {
  declare module.exports: $Exports<'pmx/lib/utils/BinaryHeap'>;
}
declare module 'pmx/lib/utils/datachecker.js' {
  declare module.exports: $Exports<'pmx/lib/utils/datachecker'>;
}
declare module 'pmx/lib/utils/EDS.js' {
  declare module.exports: $Exports<'pmx/lib/utils/EDS'>;
}
declare module 'pmx/lib/utils/error-callsites/index.js' {
  declare module.exports: $Exports<'pmx/lib/utils/error-callsites/index'>;
}
declare module 'pmx/lib/utils/error-callsites/node-0.10-formatter.js' {
  declare module.exports: $Exports<'pmx/lib/utils/error-callsites/node-0.10-formatter'>;
}
declare module 'pmx/lib/utils/EWMA.js' {
  declare module.exports: $Exports<'pmx/lib/utils/EWMA'>;
}
declare module 'pmx/lib/utils/fixedQueue.js' {
  declare module.exports: $Exports<'pmx/lib/utils/fixedQueue'>;
}
declare module 'pmx/lib/utils/probes/Counter.js' {
  declare module.exports: $Exports<'pmx/lib/utils/probes/Counter'>;
}
declare module 'pmx/lib/utils/probes/Histogram.js' {
  declare module.exports: $Exports<'pmx/lib/utils/probes/Histogram'>;
}
declare module 'pmx/lib/utils/probes/Meter.js' {
  declare module.exports: $Exports<'pmx/lib/utils/probes/Meter'>;
}
declare module 'pmx/lib/utils/proxy.js' {
  declare module.exports: $Exports<'pmx/lib/utils/proxy'>;
}
declare module 'pmx/lib/utils/sample.js' {
  declare module.exports: $Exports<'pmx/lib/utils/sample'>;
}
declare module 'pmx/lib/utils/transport.js' {
  declare module.exports: $Exports<'pmx/lib/utils/transport'>;
}
declare module 'pmx/lib/utils/units.js' {
  declare module.exports: $Exports<'pmx/lib/utils/units'>;
}
declare module 'pmx/lib/wrapper/simple_http.js' {
  declare module.exports: $Exports<'pmx/lib/wrapper/simple_http'>;
}
