// flow-typed signature: e0f05059655e63d7966956d872b8fac9
// flow-typed version: <<STUB>>/pug-html-loader_v^1.1.4/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pug-html-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pug-html-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pug-html-loader/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pug-html-loader/lib/index.js' {
  declare module.exports: $Exports<'pug-html-loader/lib/index'>;
}
