// flow-typed signature: 224c919ba903a2dad5007b93d63c6406
// flow-typed version: <<STUB>>/vue-axios_v^2.0.2/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-axios'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-axios' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-axios/dist/vue-axios.es5' {
  declare module.exports: any;
}

declare module 'vue-axios/dist/vue-axios.min' {
  declare module.exports: any;
}

declare module 'vue-axios/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-axios/dist/vue-axios.es5.js' {
  declare module.exports: $Exports<'vue-axios/dist/vue-axios.es5'>;
}
declare module 'vue-axios/dist/vue-axios.min.js' {
  declare module.exports: $Exports<'vue-axios/dist/vue-axios.min'>;
}
declare module 'vue-axios/src/index.js' {
  declare module.exports: $Exports<'vue-axios/src/index'>;
}
